# The Docker image that will be used to build your app
image: python:3.8-slim-buster

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
    - python edit.py 
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache:
    key: count-cache
    paths:
      - cache/
