version: '3'
services:
  app:
    image: eink_connector:tag
    build: .
    container_name: eink_connector
    ports:
      - "5000:8000"
    volumes:
      - ./app/log:/app/app/log
      - ./cache:/app/cache
